ALTER TABLE notifications
ADD COLUMN sender_id INT NULL,
ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'SENT',
ADD COLUMN send_to VARCHAR(20) NULL,
ADD COLUMN room_ids JSON NULL,
ADD COLUMN sent_at DATETIME NULL;
