spring.application.name=RoomManagementSystem
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=86400000
jwt.refresh-token-expiration=604800000

# Tomcat Port
server.port=8081
server.servlet.context-path=/

# CORS & Security
cors.allowed-origins=http://localhost:4200
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=*
cors.allow-credentials=true

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=./images/

# ===================================
# VNPAY CONFIGURATION (SANDBOX)
# ===================================
vnp.tmnCode=${VNPAY_TMN_CODE}
vnp.hashSecret=${VNPAY_HASH_SECRET}
vnp.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp.returnUrl=http://localhost:4200/tenant/vnpay-return


vnp.ipnUrl=http://localhost:8080/api/payments/vnpay-ipn
